### ISSUE TITLE
Docs page: Title

### ISSUE THREAD

**Issue by AllanSaku** [HYF-Class21/agile-development-group2-loruki-rebuild#47]
- [ ] This feature developed on a branch docs-pagetitle
- [ ] add `div` element with class name `navbar`
- [ ] inside the `div` add `h1` with `a` tag inside for the title of "Loruki"
- [ ] add class name `logo` to `h1`

**Comment by HeemahMuslad** [comment]
Thanks for this issue, i don't know if i am contributing the right way . just started contributing.
<div class="navbar">
        <h1 class="logo"><a href="">Loruki</a></h1>
      </div>
